


name: first git action

on:
   push

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: hello print
        run: echo "Hello from GitHub Actions!"

      - name: current datetime
        run: echo $(date)

      - name: get os name
        run: echo $(hostname)

      - name: error get
        run: apt-get update | echo "not work update"

      - name: list of files
        run: echo $(ls -la)

      - name: repo branch name
        run: echo "Branch name :- ${{ github.ref_name }}"
